<a href="https://colab.research.google.com/github/Pavankuamr14/deeplearning/blob/main/Incident_Root_Cause_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
df=pd.read_csv('/content/drive/MyDrive/Ex_Files_Deep_Learning_Getting_Started/Ex_Files_Deep_Learning_Getting_Started/Exercise Files/root_cause_analysis.csv')

In [17]:
df

ID  CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  \
0       1         0                 0      0           0           1   
1       2         0                 0      0           0           0   
2       3         0                 1      1           0           0   
3       4         0                 1      0           1           1   
4       5         1                 1      0           1           0   
..    ...       ...               ...    ...         ...         ...   
995   996         0                 0      0           0           0   
996   997         0                 0      0           1           0   
997   998         1                 1      1           0           0   
998   999         0                 1      1           1           1   
999  1000         1                 0      0           0           1   

     ERROR_1002  ERROR_1003      ROOT_CAUSE  
0             0           1     MEMORY_LEAK  
1             0           1     MEMORY_LEAK  
2             1           1     MEMORY_LEAK  
3             0           1     MEMORY_LEAK  
4             1           0   NETWORK_DELAY  
..          ...         ...             ...  
995           0           1  DATABASE_ISSUE  
996           0           0   NETWORK_DELAY  
997           0           0     MEMORY_LEAK  
998           0           0   NETWORK_DELAY  
999           1           0  DATABASE_ISSUE  

[1000 rows x 9 columns]

In [18]:
# we can see that the target variable are assigned as categorical data(in string format)
# we need to use the label encoder to convert string format into numeric format

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['ROOT_CAUSE']=le.fit_transform(df['ROOT_CAUSE'])


In [19]:
# lets see checck whether data is changed or not
df.head()

ID  CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  ERROR_1002  \
0   1         0                 0      0           0           1           0   
1   2         0                 0      0           0           0           0   
2   3         0                 1      1           0           0           1   
3   4         0                 1      0           1           1           0   
4   5         1                 1      0           1           0           1   

   ERROR_1003  ROOT_CAUSE  
0           1           1  
1           1           1  
2           1           1  
3           1           1  
4           0           2

In [20]:
# in above dataset we can observe that target variable ROOT_CAUSE catergorical data is chaged into numerical data
# Now we split the dataset into features and target



X=df.iloc[:,1:8]
print(X)
print(f"X___________________________________shape{X.shape}")
y=df.iloc[:,-1]
print(y)
print(f"y___________________________________shape{y.shape}")


     CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  ERROR_1002  \
0           0                 0      0           0           1           0   
1           0                 0      0           0           0           0   
2           0                 1      1           0           0           1   
3           0                 1      0           1           1           0   
4           1                 1      0           1           0           1   
..        ...               ...    ...         ...         ...         ...   
995         0                 0      0           0           0           0   
996         0                 0      0           1           0           0   
997         1                 1      1           0           0           0   
998         0                 1      1           1           1           0   
999         1                 0      0           0           1           1   

     ERROR_1003  
0             1  
1             1  
2        

In [21]:
# now lets convert the dataset into array format
df= df.to_numpy()
df

array([[   1,    0,    0, ...,    0,    1,    1],
       [   2,    0,    0, ...,    0,    1,    1],
       [   3,    0,    1, ...,    1,    1,    1],
       ...,
       [ 998,    1,    1, ...,    0,    0,    1],
       [ 999,    0,    1, ...,    0,    0,    2],
       [1000,    1,    0, ...,    1,    0,    0]])

In [22]:
df

array([[   1,    0,    0, ...,    0,    1,    1],
       [   2,    0,    0, ...,    0,    1,    1],
       [   3,    0,    1, ...,    1,    1,    1],
       ...,
       [ 998,    1,    1, ...,    0,    0,    1],
       [ 999,    0,    1, ...,    0,    0,    2],
       [1000,    1,    0, ...,    1,    0,    0]])

In [23]:
df.shape

(1000, 9)

In [28]:
X_data=df[:,1:8]
print(X_data)

[[0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 1]
 [0 1 1 ... 0 1 1]
 ...
 [1 1 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]
 [1 0 0 ... 1 1 0]]


In [29]:
X_data.shape

(1000, 7)

In [30]:
y_data=df[0:,-1]
print(y_data)
print(y.shape)

[1 1 1 1 2 2 2 0 1 2 1 0 1 0 2 1 1 1 2 1 2 1 1 1 2 1 1 2 2 1 0 1 1 2 1 0 1
 0 0 2 2 0 1 0 2 2 2 0 2 0 1 0 0 0 2 1 2 1 0 0 2 1 0 1 2 1 0 0 1 2 1 0 1 0
 2 1 2 2 2 2 2 1 2 1 2 2 0 1 1 0 1 1 1 1 1 2 0 1 1 1 1 1 2 0 1 2 2 0 0 1 2
 2 2 0 0 0 1 1 1 2 1 0 2 0 0 2 2 2 1 0 2 1 0 0 0 0 0 2 1 1 2 0 0 1 0 2 1 2
 0 2 2 1 0 2 0 0 0 2 2 1 2 2 2 0 2 2 1 0 1 1 0 1 2 1 1 0 1 1 1 0 2 1 0 0 1
 0 1 2 0 1 1 1 2 1 2 0 0 0 0 1 0 2 1 1 0 2 0 1 1 0 0 0 2 0 0 0 1 2 0 1 0 0
 2 1 2 2 0 1 0 2 2 2 0 0 2 2 2 1 1 1 2 0 2 0 2 0 2 1 0 1 2 1 2 2 1 2 0 0 2
 2 1 1 0 0 0 1 0 2 2 1 0 2 2 0 0 0 2 2 0 2 1 2 0 0 2 0 2 2 2 0 0 0 0 1 1 0
 2 1 2 0 1 1 1 1 2 2 2 0 1 2 1 0 1 0 2 1 1 1 2 1 2 1 1 1 2 1 1 2 2 1 0 1 1
 2 1 0 1 0 0 2 2 0 1 0 2 2 2 0 2 0 1 0 0 0 2 1 2 1 0 0 2 1 0 1 2 1 0 0 1 2
 1 0 1 0 2 1 2 2 2 2 2 1 2 1 2 2 0 1 1 0 1 1 1 1 1 2 0 1 1 1 1 1 2 0 1 2 2
 0 0 1 2 2 2 0 0 0 1 1 1 2 1 0 2 0 0 2 2 2 1 0 2 1 0 0 0 0 0 2 1 1 2 0 0 1
 0 2 1 2 0 2 2 1 0 2 0 0 0 2 2 1 2 2 2 0 2 2 1 0 1 1 0 1 2 1 1 0 1 1 1 0 2
 1 0 0 1 0 1 2 0 1 1 1 2 

In [31]:
# now let us split our dataset into training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.3, random_state=101)

In [32]:
X_train

array([[1, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0]])

In [33]:
X_train.shape

(700, 7)

In [34]:
X_test

array([[1, 0, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 0, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [1, 1, 0, ..., 1, 1, 0]])

In [35]:
X_test.shape

(300, 7)

In [36]:
y_train

array([0, 0, 1, 1, 2, 0, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 0, 0, 0,
       1, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 1, 2, 1,
       0, 2, 1, 2, 0, 1, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0,
       1, 2, 2, 2, 1, 0, 1, 1, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       1, 2, 0, 2, 1, 0, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 2, 2, 0, 0,
       2, 0, 2, 1, 2, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 2, 2, 1, 0,
       1, 0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 2, 1, 2, 1, 1, 1,
       2, 0, 1, 2, 2, 1, 2, 2, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2,
       0, 2, 2, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 2, 2, 0, 2, 0, 0, 1, 0, 2,
       1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 2, 2, 1, 0, 1, 2,
       1, 0, 1, 2, 0, 0, 1, 0, 2, 2, 2, 2, 2, 1, 1, 2, 1, 0, 0, 1, 1, 2,
       0, 0, 1, 1, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 2, 0, 1, 2, 1, 2, 2, 0,
       2, 2, 2, 0, 2, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2,

In [37]:
y_train.shape

(700,)

In [38]:
y_test

array([0, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1,
       0, 0, 1, 2, 1, 2, 0, 0, 1, 0, 0, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2, 0,
       0, 1, 1, 0, 2, 0, 0, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 2, 0,
       2, 1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2, 2, 1, 2, 0,
       2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0,
       0, 2, 2, 0, 0, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2,
       2, 1, 0, 1, 0, 2, 1, 2, 1, 2, 2, 0, 1, 2, 1, 1, 2, 1, 2, 0, 2, 1,
       2, 1, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2, 1, 0, 1, 1, 0, 1, 2, 2, 1,
       0, 2, 0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 0,
       1, 1, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 2, 1, 1, 2,
       0, 1, 2, 0, 0, 1, 0, 2, 2, 0, 2, 1, 1, 2, 2, 1, 0, 2, 1, 0, 0, 0,
       1, 0, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 0, 1, 1, 1, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 0, 2, 1, 1, 0,
       1, 1, 0, 0, 2, 2, 2, 1, 0, 1, 2, 2, 1, 0])

In [39]:
y_test.shape

(300,)

In [41]:
# since the target variable is multi-class we will use one hot encoding to create three columns with each column represnting a species.


# first create a scaler model that fit on the input data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_data)

scaler


StandardScaler()

In [42]:
# scale the numerci feature variables

X_data = scaler.transform(X_data)

X_data

array([[-0.94548368, -0.84747452, -0.80632811, ...,  1.03046381,
        -0.87210285,  1.27462619],
       [-0.94548368, -0.84747452, -0.80632811, ..., -0.97043679,
        -0.87210285,  1.27462619],
       [-0.94548368,  1.17997648,  1.24018993, ..., -0.97043679,
         1.14665375,  1.27462619],
       ...,
       [ 1.05765971,  1.17997648,  1.24018993, ..., -0.97043679,
        -0.87210285, -0.78454374],
       [-0.94548368,  1.17997648,  1.24018993, ...,  1.03046381,
        -0.87210285, -0.78454374],
       [ 1.05765971, -0.84747452, -0.80632811, ...,  1.03046381,
         1.14665375, -0.78454374]])

In [44]:
#  convert target variables as a one-hot-encoding array

y_data = tf.keras.utils.to_categorical(y_data,3)

y_data

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [52]:
# Finally we need to split the data set into trainning and testing  dataset

# we allocat 10 % of the data set is allocated for testting

X_train, X_test, Y_train, Y_test = train_test_split( X_data, y_data, test_size= 0.30)



In [53]:
X_train

array([[ 1.05765971, -0.84747452, -0.80632811, ..., -0.97043679,
         1.14665375, -0.78454374],
       [-0.94548368,  1.17997648, -0.80632811, ..., -0.97043679,
         1.14665375,  1.27462619],
       [ 1.05765971, -0.84747452,  1.24018993, ..., -0.97043679,
         1.14665375, -0.78454374],
       ...,
       [-0.94548368,  1.17997648,  1.24018993, ...,  1.03046381,
        -0.87210285, -0.78454374],
       [-0.94548368, -0.84747452,  1.24018993, ...,  1.03046381,
        -0.87210285,  1.27462619],
       [-0.94548368, -0.84747452,  1.24018993, ...,  1.03046381,
         1.14665375, -0.78454374]])

In [54]:
 X_test

array([[ 1.05765971,  1.17997648, -0.80632811, ...,  1.03046381,
         1.14665375, -0.78454374],
       [-0.94548368,  1.17997648, -0.80632811, ...,  1.03046381,
        -0.87210285, -0.78454374],
       [-0.94548368, -0.84747452,  1.24018993, ..., -0.97043679,
        -0.87210285, -0.78454374],
       ...,
       [ 1.05765971, -0.84747452, -0.80632811, ...,  1.03046381,
         1.14665375,  1.27462619],
       [-0.94548368,  1.17997648, -0.80632811, ..., -0.97043679,
        -0.87210285, -0.78454374],
       [-0.94548368,  1.17997648, -0.80632811, ..., -0.97043679,
        -0.87210285, -0.78454374]])

In [55]:
 Y_train

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [56]:
 Y_test

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0

In [57]:
# lets check the shape of the train and test datasets

X_train.shape

(700, 7)

In [58]:
X_test.shape

(300, 7)

In [59]:
Y_train.shape

(700, 3)

In [60]:
Y_test.shape

(300, 3)

In [74]:
# now lets build model and evaluate the model
from tensorflow import keras
# for build the model we need to know the input feature size that is 7 and we have the 2 classes in traget variable
OUT_PUT_TARGET_CLASSES=3
INPUT_FEATURES_SIZE=7

import tensorflow as tf
# we will use the sequencial model in keras
model=tf.keras.models.Sequential()

# first input layer
model.add(tf.keras.layers.Dense(128,
                               input_shape=(INPUT_FEATURES_SIZE,),
                                name= 'input_layer',
                                activation='relu'))

# first hidden layer
model.add(tf.keras.layers.Dense(64,
                                name= 'hidden_layer1',

                                activation='relu'))
#second hidden layer
model.add(tf.keras.layers.Dense(32,
                                name= 'hidden_layer2',

                                activation='relu'))
#output layer
model.add(tf.keras.layers.Dense(OUT_PUT_TARGET_CLASSES,
                                name= 'output_layer',
                                activation='softmax'))
# compile the model with loss and metrices
model.compile(
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()



Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_layer (Dense)         (None, 128)               1024      
                                                                 
 hidden_layer1 (Dense)       (None, 64)                8256      
                                                                 
 hidden_layer2 (Dense)       (None, 32)                2080      
                                                                 
 output_layer (Dense)        (None, 3)                 99        
                                                                 
Total params: 11459 (44.76 KB)
Trainable params: 11459 (44.76 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [75]:
# lets train our model and also evaluate the model

VERBOSE=1
# set batch size

BATCH_SIZE = 16

# set number of epochs

EPOCHS= 10

# set validation split. 20 % of the training data will be use for validation

# after each epoch

VALIDATION_SPLIT=0.2


# X_train, X_test, y_train, y_test

history=model.fit(X_train,
                  Y_train,
                  batch_size=BATCH_SIZE,
                  epochs=EPOCHS,
                  verbose=VERBOSE,
                  validation_split=VALIDATION_SPLIT)

#Evaluate the model against the test dataset and print results
print("\nEvaluation against Test Dataset :\n------------------------------------")
model.evaluate(X_test,Y_test)

Epoch 1/10
35/35 [==============================] - 1s 11ms/step - loss: 0.7188 - accuracy: 0.7696 - val_loss: 0.5004 - val_accuracy: 0.8286
Epoch 2/10
35/35 [==============================] - 0s 3ms/step - loss: 0.4886 - accuracy: 0.8304 - val_loss: 0.4484 - val_accuracy: 0.8214
Epoch 3/10
35/35 [==============================] - 0s 3ms/step - loss: 0.4496 - accuracy: 0.8232 - val_loss: 0.4223 - val_accuracy: 0.8429
Epoch 4/10
35/35 [==============================] - 0s 3ms/step - loss: 0.4315 - accuracy: 0.8339 - val_loss: 0.4185 - val_accuracy: 0.8500
Epoch 5/10
35/35 [==============================] - 0s 3ms/step - loss: 0.4179 - accuracy: 0.8339 - val_loss: 0.4067 - val_accuracy: 0.8500
Epoch 6/10
35/35 [==============================] - 0s 3ms/step - loss: 0.3989 - accuracy: 0.8554 - val_loss: 0.4051 - val_accuracy: 0.8571
Epoch 7/10
35/35 [==============================] - 0s 3ms/step - loss: 0.3909 - accuracy: 0.8500 - val_loss: 0.4014 - val_accuracy: 0.8643
Epoch 8/10
35/35 [=

[0.4187473952770233, 0.8533333539962769]

In [77]:
# so we have done our training process now lets look at prediction of an example

CPU_LOAD=1
MEMORY_LOAD=1
DELAY=1
ERROR_1000=2
ERROR_1001=4
ERROR_1002=4
ERROR_1003=2


prediction=np.argmax(model.predict(
    [[CPU_LOAD,MEMORY_LOAD,DELAY,
      ERROR_1000,ERROR_1001,ERROR_1002,ERROR_1003]]), axis=1 )

print(le.inverse_transform(prediction))


1/1 [==============================] - 0s 236ms/step
['DATABASE_ISSUE']
